name: Contrôle Qualité JS et Déploiement Doc

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  analyse_et_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonage du dépôt
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installation des dépendances
        run: npm install

      - name: Linter JavaScript (Nommage S_, I_, B_)
        run: npm run lint:js

      - name: Génération de la JSDoc
        run: npm run doc

      - name: Déploiement sur GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs